# Generated by Django 4.1 on 2023-12-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg.card')),
                ('deck_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg.deck')),
            ],
        ),
    ]
