# Generated by Django 4.1 on 2023-12-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0003_deck_contains'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contains',
            table='contains',
        ),
        migrations.AlterModelTable(
            name='deck',
            table='deck',
        ),
    ]
