# Generated by Django 4.1 on 2023-12-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0004_alter_contains_table_alter_deck_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='user_key',
        ),
        migrations.DeleteModel(
            name='Contains',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
