# Generated by Django 4.1 on 2023-12-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0007_contains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contains',
            name='cardname',
            field=models.ForeignKey(db_column='cardname', on_delete=django.db.models.deletion.CASCADE, to='mtg.card', to_field='name'),
        ),
        migrations.AlterField(
            model_name='contains',
            name='deckname',
            field=models.ForeignKey(db_column='deckname', on_delete=django.db.models.deletion.CASCADE, to='mtg.deck', to_field='deckname'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='mtg.user', to_field='username'),
        ),
    ]
