# Generated by Django 4.1 on 2023-12-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0010_rename_contains_contain_alter_contain_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(null=True),
        ),
    ]
